---

- name: prepare
  include_tasks: prepare.yml

- name: install
  include_tasks: install.yml

- name: configure
  include_tasks: configure/main.yml

#- name: service
#  include_tasks: service.yml

...
