---

- name: include OS specific configuration ({{ ansible_distribution }} ({{ ansible_os_family }}) {{ ansible_distribution_major_version }})
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      paths:
        - "vars"
      files:
        # eg. debian-10 / ubuntu-20.04 / centos-8 / oraclelinux-8
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
        # eg. archlinux-systemd / archlinux-openrc
        - "{{ ansible_distribution | lower }}-{{ ansible_service_mgr | lower }}.yml"
        # eg. debian / ubuntu / centos / oraclelinux
        - "{{ ansible_distribution | lower }}.yml"
        # eg. redhat / debian / archlinux
        - "{{ ansible_os_family | lower }}.yml"
        - default.yaml
      skip: true

- name: update package cache
  package:
    update_cache: true

- name: install dependency
  package:
    name: "{{ ds389_requirements }}"
    state: present
  when:
    - ds389_requirements is defined
    - ds389_requirements | count > 0

- name: merge ds389 init_general configuration between defaults and custom
  set_fact:
    ds389_init_general: "{{ ds389_defaults_init_general |
      combine( ds389_init_general, recursive=True ) }}"

- name: merge ds389 init_slapd configuration between defaults and custom
  set_fact:
    ds389_init_slapd: "{{ ds389_defaults_init_slapd |
      combine( ds389_init_slapd, recursive=True ) }}"

- name: merge ds389 init_backend configuration between defaults and custom
  set_fact:
    ds389_init_backend: "{{ ds389_defaults_init_backend |
      combine( ds389_init_backend, recursive=True ) }}"

- name: merge ds389 tls configuration between defaults and custom
  set_fact:
    ds389_tls: "{{ ds389_defaults_tls |
      combine( ds389_tls, recursive=True ) }}"

- name: merge ds389 logging configuration between defaults and custom
  set_fact:
    ds389_logging: "{{ ds389_defaults_logging |
      combine( ds389_logging, recursive=True ) }}"



...
