---
- name: converge
  hosts: all
  any_errors_fatal: false

  environment:
    NETRC: ''

  roles:
    - role: ansible-389ds


  post_tasks:
    - name: Ensure container entries exist, for testing
      ldap_entry:
        server_uri: "ldap://localhost"
        bind_dn: "cn=Directory Manager"
        bind_pw: "secret"
        dn: "{{ item.dn }}"
        objectClass: "{{ item.objectClass }}"
        state: present
      loop:
        - dn: "ou=Groups,dc=example,dc=local"
          objectClass:
            - organizationalunit
            - top
        - dn: "ou=People,dc=example,dc=local"
          objectClass: ["organizationalunit", "top"]
      register: dirsrv_test_containers
      failed_when: dirsrv_test_containers.changed
