---

snakeoil_local_tmp_directory: "{{
  lookup('env', 'CUSTOM_LOCAL_TMP_DIRECTORY') |
  default(lookup('env', 'HOME') ~ '/.cache/ansible/snakeoil', true) }}"

ds389_init_slapd:
  root_password: "Bwmo5xqKeXDg2xkhFwhNLG1k8G9fUfS9q5FQ70I8uD"

ds389_init_backend:
  molecule.com:
    name: moleculeRoot
    sample_entries: false
    suffix: dc=molecule,dc=lan
    create_suffix_entry: true

ds389_custom_schema:
  - "98-ssh.ldif"
  - "98-telegram.ldif"

ds389_plugins_enabled:
  MemberOf Plugin: true
  # Distributed Numeric Assignment Plugin: true

ds389_tls:
  enabled: true
  enforced: true
  key_file: "{{ snakeoil_local_tmp_directory }}/{{ snakeoil_domain }}/{{ snakeoil_domain }}.key"
  cert_file: "{{ snakeoil_local_tmp_directory }}/{{ snakeoil_domain }}/{{ snakeoil_domain }}.pem"

...
