---

- name: check if instance directory exists
  stat:
    path: "/var/lib/dirsrv/slapd-{{ ds389_init_slapd.instance_name }}"
  register: ds389_instance_dir

- name: check if {{ ds389_init_slapd.instance_name }} instance directory exists
  set_fact:
    ds389_instance_dir_exists: "{{ ds389_instance_dir.stat.exists and ds389_instance_dir.stat.isdir }}"

- block:
    - name: create installation template
      template:
        src: templates/install.inf.j2
        dest: /tmp/install.inf
        mode: '600'
      when:
        - not ds389_instance_dir_exists

    # On newer versions of 389ds setup-ds.pl got deprecated and separated in a legacy package
    # Here we're using the modern equivalent, with a completely different API ...
    - name: run installation script (dscreate)
      become: true
      dscreate:
        from_file: /tmp/install.inf
        verbose: true
      register: _dscreate
      #command: |
      #  /usr/sbin/dscreate \
      #    from-file /tmp/install.inf
      when:
        - not ds389_instance_dir_exists

    - name: copy additional ldif files (dsconf)
      copy:
        src: "{{ item }}"
        dest: "{{ ds389_install_additional_ldif_dir }}/{{ item | basename }}"
        mode: '400'
        owner: dirsrv
        group: dirsrv
      when:
        - not ds389_instance_dir_exists
      loop: "{{ ds389_install_additional_ldif }}"

    # The newer version of the install.ini file does not have a InstallLdifFile object anymore
    # So we manually install extra ldifs later
    - name: install additional ldif files (dsconf)
      dsconf:
        instance: "{{ ds389_init_slapd.instance_name }}"
        resources:
          - backend
          - import
          - "{{ ds389_init_backend.[0].name }}"
          - "{{ ds389_install_additional_ldif_dir }}/{{ item | basename }}"
        verbose: true
      # command: >
      #   /usr/sbin/dsconf
      #   {{ ds389_init_slapd.instance_name }}
      #   backend import
      #   {{ ds389_init_backend.[0].name }}
      #   {{ ds389_install_additional_ldif_dir }}/{{ item | basename }}
      when:
        - not ds389_instance_dir_exists
      loop: "{{ ds389_install_additional_ldif }}"

    - name: delete temporary additional ldif files (dsconf)
      file:
        path: "{{ ds389_install_additional_ldif_dir }}/{{ item | basename }}"
        state: absent
      when:
        - not ds389_instance_dir_exists
      loop: "{{ ds389_install_additional_ldif }}"

  when:
    - not ds389_instance_dir_exists

  always:
    - name: remove installation template
      file:
        state: absent
        path: /tmp/install.inf

# einmal okay, aber bei jedem lauf!?
- name: restart 389ds {{ ds389_init_slapd.instance_name }} instance
  become: true
  service:
    name: "dirsrv@{{ ds389_init_slapd.instance_name }}"
    state: restarted

...
