---

- name: d
  debug:
    msg:
      - "{{ ds389_plugins_enabled }}"
      # - "{{ 'Distributed Numeric Assignment Plugin' in ds389_plugins_enabled }}"
      # - "{{ ds389_plugins_enabled['Distributed Numeric Assignment Plugin'] }}"

- name: enable plugins dynamic load
  ldap_attrs:
    state: exact
    server_uri: "{{ ds389_server_uri }}"
    validate_certs: "{{ ds389_tls.validate_certs }}"
    start_tls: "{{ ds389_starttls_early }}"
    bind_dn: "{{ ds389_init_slapd.root_dn }}"
    bind_pw: "{{ ds389_init_slapd.root_password }}"
    dn: "cn=config"
    attributes:
      nsslapd-dynamic-plugins: "{{ 'on' if ds386_plugins_dynamic_load else 'off' }}"

- name: enable plugins
  ldap_attrs:
    state: exact
    server_uri: "{{ ds389_server_uri }}"
    validate_certs: "{{ ds389_tls.validate_certs }}"
    start_tls: "{{ ds389_starttls_early }}"
    bind_dn: "{{ ds389_init_slapd.root_dn }}"
    bind_pw: "{{ ds389_init_slapd.root_password }}"
    dn: "cn={{ item.key }},cn=plugins,cn=config"
    attributes:
      nsslapd-pluginEnabled: "{{ 'on' if item.value else 'off' }}"
  loop: "{{ ds389_plugins_enabled | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  notify:
    - restart ds389

- name: Distributed Numeric Assignment
  include_tasks: configure/plugins/distributed-numeric-assignment.yml
  when:
    - "'Distributed Numeric Assignment Plugin' in ds389_plugins_enabled"
    - ds389_plugins_enabled['Distributed Numeric Assignment Plugin']

...
